### PR TITLE
Adding working-directory command in maven.yml (GitHub actions).

### PR DESCRIPTION
**Pull request by sudo-githubuser**

### CODE REVIEW

**Review by i-ampraveen — CHANGES_REQUESTED** [review]
Build is failing, change the working-directory value.

**Comment by sudo-githubuser** [comment]
> Build is failing, change the working-directory value.

changes done.

**Comment by i-ampraveen** [comment]
> > Build is failing, change the working-directory value.
> 
> changes done.

build failing as POM file is in root directory. Fix it.

**Comment by i-ampraveen** [comment]
> > > Build is failing, change the working-directory value.
> > 
> > 
> > changes done.
> 
> build failing as POM file is in root directory. Fix it.

build is passed but no tests are getting executed. Specify the working directory in POM file only.

**Review by i-ampraveen — APPROVED** [review]

**Pull request merged**
